REM THis IS COMMNET IN BATCH PROGRAMMING ADN REM IS USED FOR IT.

REM DEVELOPLED BY DEEPAK PATRE.

ECHO OFF
CLS
COLOR 0A
ECHO WELCOME MR. %username% IN CUI BASED WORLD.......
ECHO THE CURRENT DATE IS %DATE%
ECHO AND THE CURRENT TIME %TIME%
PAUSE